# Generated by Django 5.0.6 on 2026-07-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveIntegerField(help_text='1 = first day of trip, 2 = second, ...')),
                ('date_label', models.CharField(blank=True, max_length=20)),
                ('total_driving_hours', models.FloatField(default=0)),
                ('total_on_duty_hours', models.FloatField(default=0)),
                ('total_off_duty_hours', models.FloatField(default=0)),
                ('total_sleeper_hours', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['day_index'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('current_location_lat', models.FloatField(blank=True, null=True)),
                ('current_location_lng', models.FloatField(blank=True, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_location_lat', models.FloatField(blank=True, null=True)),
                ('pickup_location_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_location_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_location_lng', models.FloatField(blank=True, null=True)),
                ('current_cycle_used_hours', models.FloatField(help_text="Hours already used in the driver's 70hr/8-day cycle")),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_driving_hours', models.FloatField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=3)),
                ('start_hour', models.FloatField(help_text='0-24, hour of day this segment starts')),
                ('end_hour', models.FloatField(help_text='0-24, hour of day this segment ends')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('log_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.logsheet')),
            ],
            options={
                'ordering': ['start_hour'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff'), ('FUEL', 'Fuel'), ('REST_BREAK', '30-min Rest Break'), ('OVERNIGHT', '10-hr Off Duty / Overnight'), ('RESTART_34', '34-hr Restart')], max_length=20)),
                ('sequence', models.PositiveIntegerField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('trip_hour_start', models.FloatField(help_text='Hours elapsed since trip start')),
                ('trip_hour_end', models.FloatField(help_text='Hours elapsed since trip start')),
                ('duration_hours', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='logsheet',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.trip'),
        ),
    ]
