# Generated by Django 5.0.6 on 2026-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='distance_at_stop_miles',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
